### ISSUE TITLE
Support time subtraction to get a duration

### ISSUE THREAD

**Issue by rosejn** [juxt/tick#152]
Hi,
  I found the t/between function to get a duration spanning two instants, and I thought it would be natural to add support for subtraction to perform the same thing, which is actually what I tried first.  I forked and was going to add this and issue a PR, but the ITimeArithmetic protocol requires both addition and subtraction.  How about splitting these into separate protocols so that we can add support for subtracting instants, dates, etc. to get a duration, which is logically how most people will likely think about it?

https://github.com/juxt/tick/blob/f47c3efd7f56f8ca59cb1f960d731d199217f986/src/tick/core.cljc#L739

Thanks for tick!  We're using it all over a project now with great success.

**Comment by henryw374** [comment]
Thanks! Good to hear.

I think this behaviour is met by between. I think you can negate durations, or absolute them if you need pos/neg of the result.

Also +/- are meant to be analagous to clojure.core +/- , commutative etc. so not suitable for date args.

Closing, but pls reopen if more discussion required

**Comment by rosejn** [comment]
So on second thought I don't quite understand you here.  In Clojure and math in general subtraction isn't commutative.  The ordering of terms does impact the outcome of a subtraction.  Given that dates are actually points on a number line, identical to the integers (which is why we can use seconds or milliseconds since the epoch to represent them) it seems very natural to subtract one date from another to determine the difference in time, no?  

We're using between for this functionality so it's not a big deal, but in terms of creating an API that makes it natural to work with datetimes this feels like something many people would expect to do.  Maybe just a design choice though, so your call.  That's my 2 cents.

**Comment by henryw374** [comment]
Thanks, yes I could have explained this better here. 

Yes only + is commutative and when I said that, it's more my shorthand for the character or general usage of the functions - I will be more precise in future. Consider `(+ a b c d ....)` or `(- a b c d ...)`, is anyone likely to do that when some of the args are points on a timeline... I'd say not. I think the only case that makes sense where more than one of the args is a date, is `(- a b)`. Since that already has special treatment in java.time with the between/until methods (some of which allow you to specify output unit), I'd prefer to use that. There's also the complication of the output type. With the current +/- it's obvious, but if the args can be dates (viewed as points on a timeline) and I add two dates, maybe I should get another date back? There's a ticket open atm for introduction of a multiply `*` function. That'll fit alongside the existing +/-/divide well. I can't imagine using that for 2 or more dates. 

Re point on a number line, I agree Instant, zdt etc can be viewed as nanos offset, but other types like LocalDate and LocalDateTime I would say should not be, or at least are on much shakier ground. With java.util.Date, I think subtracting the epoch millis was the only way to calc difference - but that was fairly manual, get the mills, do some math. 

I feel I could cut down my response here if I gave it more time. Am I making sense?
