### ISSUE TITLE
run tests via hooks for pull requests

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#97]
there are circleci tests, but these don't run automatically for pull requests for some reason. 

fixing this would make it much easier/faster to accept PRs of course.

possibly move to github actions if that would make setup easier?

**Comment by cksharma11** [comment]
@henryw374 

You can’t trigger a build with a pull request unfortunately, not that I know of. The reason is, because there is no commit to run. The pull request hasn’t actually made any changes in the code, so there is nothing to run. That is why it only runs when you merge the request.

https://discuss.circleci.com/t/pull-requests-not-triggering-build/1213/4
